# Nivell 1
## 1.

In [1]:
import pandas as pd

# Importamos el archivo saltándonos las 3 primeras filas de títulos
df = pd.read_excel(r"C:\Users\aleja\Documents\Analisis de Datos\Especialidad IT ACADEMY\Sprint 10 Analítica de dades en Python\Sprint 10 ARCHIVOS\sprint10.xlsx", skiprows=3)

# Eliminamos la columna repetida de indice q no necesitamos (borramos por nombre de columna)
df = df.drop(columns=['Unnamed: 0'])

# Ordenamos por País y luego por Ciutat
df_ordenado = df.sort_values(by=["País d'origen", "Ciutat"])
df_ordenado

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A

In [3]:
# Mostramos las primeras 10 filas del dataframe ordenado por pais y ciudad
df_ordenado.head(10)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

In [2]:
# Comprobamos si la columna 'DNI' tiene valores únicos
print(df_ordenado['DNI'].is_unique)

#Tambien podemos comprobar comparando la cantidad de filas con los DNI unicos
df['DNI'].nunique() == len(df)

True

True

## 2.

In [3]:
#Crea una columna que sigui el nom complet.
df['Nombre Completo'] = df['Nom'] + ' ' + df['Cognoms']

#Crea una columna si la persona és nascuda a Espanya o no.
df['Nacido en España']=df["País d'origen"]=='Espanya'

#Posa el DNI com a índex del DataFrame (noms de files).
#Usamos un if para evitar errores en caso de ejecutar mas de 1 vez la celda
if 'DNI' in df.columns:
    df=df.set_index('DNI')

#Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
df=df.rename(columns={'Dia de Naixement':'Dia',
                     'Mes de Naixement':'Mes',
                      'Any de Naixement':'Año'})

#Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
df['Gènere']=df['Gènere'].replace({
    'D':"Mujer",
    'H':"Hombre",
    'NC': None,
    'A':'Otros'
})


#Notamos valores nulos en el genero asi que borramos
nulos_antes = df["Gènere"].isna().sum()
print(f"Filas con género vacío antes de limpiar: {nulos_antes}")

# borramos solo las filas donde 'Gènere' sea nulo
df = df.dropna(subset=["Gènere"])

# Comprobamos que el marcador haya bajado a 0
nulos_despues = df["Gènere"].isna().sum()
print(f"Filas con género vacío después de limpiar: {nulos_despues}")

#Mostra tots els canvis que has realitzat en una sola taula.
df.head()

Filas con género vacío antes de limpiar: 60
Filas con género vacío después de limpiar: 0

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre Completo,Nacido en España
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva,False
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez,True
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1.441 €,1.0,NaN,Grup A,Fatima Fassi,False
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani,False
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1.043 €,NaN,1.0,Grup A,Toni Sánchez García,True

## 3.
Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [4]:
#Creamos una funcion que analizara cada fila y nos dara la respuesta segun el booleano en la columna Fills

def calculo_hijos(fila):
    if fila['Fills']==True:
        return 'Si'
    else:
        return 'No'
    
#Creamos la columna nueva unificada viajando fila por fila (axis=1)
df['Fills']=df.apply(calculo_hijos,axis=1)

#Eliminamos la columna vieja que ya es innecesaria
df=df.drop(columns=['No Fills'])

df.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,Grup Professional,Nombre Completo,Nacido en España
DNI,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1.144 €,No,Grup B,Inês Ferreira Silva,False
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1.253 €,Si,Grup A,Clara Sánchez Martínez,True
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1.441 €,Si,Grup A,Fatima Fassi,False
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1.944 €,No,Grup B,Khadija Bennani Bennani,False
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1.043 €,No,Grup A,Toni Sánchez García,True

## 4.

In [5]:
# Limpiamos la columna antes de hacer los calculos:
if df['Salari mensual'].dtype == 'object': # con el if evitamos errores al volverlo a ejecutar, comprobamos si es tipo object
    df['Salari mensual'] = df['Salari mensual'].str.replace(' €', '', regex=False)
    df['Salari mensual'] = df['Salari mensual'].str.replace('.', '', regex=False)
    df['Salari mensual'] = df['Salari mensual'].astype(float)
    
#Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.
resumen=df.groupby('Gènere')['Salari mensual'].agg(Sou_mig='mean',Sou_medià='median',Sou_max='max',Sou_min='min')

#Ordena la taula en funció del sou mig.
resumen=resumen.sort_values(by="Sou_mig")
resumen['Sou_mig']=resumen['Sou_mig'].round(2)
resumen

        Sou_mig  Sou_medià  Sou_max  Sou_min
Gènere
Mujer   1469.44     1361.5   3021.0    665.0
Otros   1626.59     1545.0   3175.0    703.0
Hombre  1643.25     1531.0   3356.0    737.0

## 5.

In [6]:
#para poder aplicar los colores se debió instalar la libreria jinja2

#Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).
tabla_resumen=pd.pivot_table(df,
    values='Salari mensual',
    index='Gènere',
    columns="País d'origen",
    aggfunc='mean', #Afegeix-hi les mitjanes als marges de la taula.
    margins=True,
    margins_name='Media Global'
)

# Redondeamos TODA la tabla dinámica a solo 2 decimales de golpe
tabla_resumen = tabla_resumen.round(2)

#(EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats
#Aplicamos el formato condicional de colores 
tabla_resumen.style.background_gradient(cmap='YlOrRd').format(precision=2) # para q solo muestre 2 decimales

## 6.
Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any. Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.

Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [7]:
#importamos la libreria y el objeto datetime
from datetime import datetime

#  Crear la columna Datetime uniendo Any, Mes y Dia, deben estar en ingles para que pandas las transforme
df['Fecha_Nacimiento'] = pd.to_datetime(
    df[['Año', 'Mes', 'Dia']].rename(columns={'Año': 'year', 'Mes': 'month', 'Dia': 'day'})
)

# Creamos la función  que calcula la edad exacta
def calcular_edad(fecha_nacimiento):
    hoy = datetime.today()
    edad = hoy.year - fecha_nacimiento.year
    
    # Restamos 1 si la fecha de hoy es anterior al día del cumpleaños este año
    if (hoy.month, hoy.day) < (fecha_nacimiento.month, fecha_nacimiento.day):
        edad -= 1
    return edad

# Aplicamos la función para rellenar la nueva columna de edad actual
df['Edad_Actual'] = df['Fecha_Nacimiento'].apply(calcular_edad)

# Mostramos las columnas de interés para comprobar que se hizo bien
df[['Fecha_Nacimiento', 'Edad_Actual']].head()

          Fecha_Nacimiento  Edad_Actual
DNI
16928694K       1953-02-25           73
27724652S       1996-03-18           30
38141675A       2005-11-06           20
59157262R       1995-01-20           31
69630528M       1999-08-09           26

# Nivell 2
## 1.
Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.

Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.

df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})

In [8]:
#creamos el nuevo df como da el enunciado:
df_increment = pd.DataFrame({
    "Grup": ["Grup A", "Grup B", "Grup C", "Grup D"], 
    "Increment": ["5%", "3,5%", "2%", "8%"]
})

#Evitamos crear columnas por error de volver a ejecutar con un if 
if 'Increment_limpio' not in df.columns: 
    
    #El merge reinicia el indice por lo que para salvar el DNI debememos pasarlo a columna normal 
    df_temporal = df.reset_index()
    
    #unimos las tablas con merge() especificando donde ya que se llaman diferente y el tipo de merge en este caso left.
    df_fusionado = pd.merge(df_temporal, df_increment, left_on='Grup Professional', right_on='Grup', how='left')

    #Ahora nos toca limpiar la columna de incremento de salario
    #Quitamos el %
    df_fusionado['Increment_limpio'] = df_fusionado['Increment'].str.replace('%', '', regex=False)

    #Cambiamos la coma por un punto
    df_fusionado['Increment_limpio'] = df_fusionado['Increment_limpio'].str.replace(',', '.', regex=False)

    #Convertimos a número flotante y lo dividimos por 100 para tener el decimal real (ej: 5% es 0.05)
    df_fusionado['Increment_limpio'] = df_fusionado['Increment_limpio'].astype(float) / 100
    
    #Borramos la columna sin limpiar que ya no necesitamos
    df_fusionado=df_fusionado.drop("Increment",axis=1)

    #Actualizamos el salario segun el porcentaje de incremento
    df_fusionado['Salari mensual'] = (df_fusionado['Salari mensual'] * (1 + df_fusionado['Increment_limpio'])).round(2)
    
    #Volvemos a subir el DNI al indice 
    df = df_fusionado.set_index('DNI')
    
else:
    print(" Celda saltada: El incremento ya estaba aplicado en esta tabla. Evitamos duplicados y errores.")


df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,Grup Professional,Nombre Completo,Nacido en España,Fecha_Nacimiento,Edad_Actual,Grup,Increment_limpio
DNI,,,,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1184.04,No,Grup B,Inês Ferreira Silva,False,1953-02-25,73,Grup B,0.035
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1315.65,Si,Grup A,Clara Sánchez Martínez,True,1996-03-18,30,Grup A,0.050
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1513.05,Si,Grup A,Fatima Fassi,False,2005-11-06,20,Grup A,0.050
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,2012.04,No,Grup B,Khadija Bennani Bennani,False,1995-01-20,31,Grup B,0.035
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1095.15,No,Grup A,Toni Sánchez García,True,1999-08-09,26,Grup A,0.050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1258.56,No,Grup B,Marta Ferrer Ferrer,True,1951-06-01,75,Grup B,0.035
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,1019.55,No,Grup A,Joan García,True,1959-04-11,67,Grup A,0.050
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,716.10,No,Grup A,Laia Ferrer Martínez,True,1980-11-11,45,Grup A,0.050
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1732.98,Si,Grup C,Jordi García,True,1984-05-23,42,Grup C,0.020
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1277.85,No,Grup A,Clara Sánchez López,True,1952-08-01,73,Grup A,0.050

## 2.
Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...

Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [9]:
#Importamos la libreria os para guardar los archivos en una carpeta
import os

carpeta_entrega = "Nivel2_ejercicio2_sprint10"
#Creamos la carpeta de forma segura. 
#exist_ok=True evita errores si vuelves a ejecutar la celda.
os.makedirs(carpeta_entrega, exist_ok=True)

print("Exportando archivos por grupo profesional...")
# Creamos el bucle para exportar cada grupo 
for grup in df['Grup Professional'].unique():
    # Filtramos los trabajadores de ese grupo concreto
    df_grup = df[df['Grup Professional'] == grup]
    
    # Limpiamos el nombre para el archivo (ej: "Grup A" -> "GrupA")
    grup_limpio = grup.replace(' ', '')
    nombre_archivo = f"datos_{grup_limpio}.xlsx"
    
    # 3. Combinamos la carpeta y el nombre del archivo en una ruta completa
    ruta_completa = os.path.join(carpeta_entrega, nombre_archivo)
    
    # Exportamos garantizando que el DNI (indice) se guarde en el archivo
    df_grup.to_excel(ruta_completa, index=True)
    print(f"Generado con éxito: {ruta_completa}")


# Creamos y exportamos ahora el 5to archivo, el archivo resumen
print("\n Generando el informe resumen de grupos ")

df_resumen_grupos = df.groupby('Grup Professional').agg(
    Trabajadores=('Nom', 'count'),    #Renombramos directamente las columnas generadas
    Salario_medio=('Salari mensual', 'mean'),
    Edad_mediana=('Edad_Actual', 'median')
).round(2) # Redondeamos los promedios a 2 decimales con round

#Definimos la ruta de la carpeta también para el archivo resumen
ruta_resumen = os.path.join(carpeta_entrega, "resumen_grupos_profesional.xlsx")

# Exportamos el informe resumen  Añadimos el encoding para que Excel lo lea bien
df_resumen_grupos.to_excel(ruta_resumen, index=True)
print("Generado con éxito:",ruta_resumen)

# Invocamos la tabla resumen para ver el resultado en pantalla
df_resumen_grupos

Exportando archivos por grupo profesional...
Generado con éxito: Nivel2_ejercicio2_sprint10\datos_GrupB.xlsx
Generado con éxito: Nivel2_ejercicio2_sprint10\datos_GrupA.xlsx
Generado con éxito: Nivel2_ejercicio2_sprint10\datos_GrupD.xlsx
Generado con éxito: Nivel2_ejercicio2_sprint10\datos_GrupC.xlsx

 Generando el informe resumen de grupos
Generado con éxito: Nivel2_ejercicio2_sprint10\resumen_grupos_profesional.xlsx

                   Trabajadores  Salario_medio  Edad_mediana
Grup Professional
Grup A                      459        1212.12          51.0
Grup B                      301        1723.85          48.0
Grup C                      130        2293.80          51.5
Grup D                       50        3105.69          43.0

# Nivell 3
El nivell 3 d’aquest sprint és totalment diferent a d’altres sprints que has fet fins ara, ja que són exercicis més abstractes que requereixen barallar-s’hi bastant. No continuen amb el mateix dataset dels nivells anteriors, sinó que et plantegen dues situacions noves totalment diferents entre elles.

## 1.
Crea una funció que prengui un dataframe com a paràmetre d'entrada.

La funció ha de crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple:

un histograma/boxplot si la variable és numèrica
unes barres dels valors més freqüents si és categòrica
unes barres dels anys més freqüents si la dada està en format data.
La idea és crear una funció que funcioni per qualsevol dataframe, no només amb el que hem treballat fins ara.

Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

Tingues en consideració que en el següent sprint treballaràs exclusivament amb gràfics. L’objectiu d’aquest exercici no és crear gràfics molt elaborats, sinó resoldre una necessitat de manera ràpida i automàtica.

In [11]:
#Importamos las librerias necesarias para hacer el ejercicio
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def generar_graficos_automaticos(dataframe):
    # Creamos la carpeta donde guardaremos todas las imagenes png
    os.makedirs("mis_graficos", exist_ok=True)
    
    for columna in dataframe.columns:
       #Quitamos los nulos de la columna antes de analizarla
        datos_limpios = dataframe[columna].dropna()
        
        # Si la columna se quedó vacía por culpa de los nulos, la saltamos
        if datos_limpios.empty:
            print(f"Saltando '{columna}': columna vacía o llena de nulos.")
            continue
            
        # Usamos try y except para evitar que el código se detenga por errores
        try:
            plt.figure(figsize=(7, 4))  #asignamos un numero para el tamaño de las imagenes
            
            # Condición para columnas numéricas
            if pd.api.types.is_numeric_dtype(datos_limpios):
                sns.histplot(x=datos_limpios, color="royalblue", kde=True)
                plt.title(f"Análisis Numérico: {columna}")
                
            # Condición para fechas
            elif pd.api.types.is_datetime64_any_dtype(datos_limpios):
                anys = datos_limpios.dt.year.value_counts().head(10)
                sns.barplot(x=anys.index, y=anys.values, color="forestgreen")
                plt.title(f"Análisis Temporal (Años): {columna}")
                
            # Condición por descarte (categóricas/texto)
            else:
                top_valores = datos_limpios.value_counts().head(10)
                sns.barplot(x=top_valores.values, y=top_valores.index, hue=top_valores.index, legend=False, palette="viridis")
                plt.title(f"Análisis Categórico (Top 10): {columna}")
                
            plt.tight_layout()
            # Guardamos especificando la ruta de la carpeta
            plt.savefig(f"mis_graficos/grafico_{columna}.png")
            plt.close() # importante cerrar la imagen porque sino se superpondrian unas a otras
            
        except Exception as e:
            print(f" Error inesperado en la columna '{columna}': {e}") #con el e mostramos el error especifico
            plt.close()
            
    print("\nProceso finalizado\nTodos los gráficos viables están guardados dentro de la carpeta 'mis_graficos'.")

#Cargamos el dataset 'titanic' de prueba
titanic = sns.load_dataset('titanic')

#Ejecutamos la función
generar_graficos_automaticos(titanic)

Proceso finalizado
Todos los gráficos viables están guardados dentro de la carpeta 'mis_graficos'.

## 2.
Carrega l'arxiu matriu_distancies.xlsx a pandas, de manera que els noms de files i els noms de columnes siguin els de les ciutats. Borra "Las Palmas de Gran Canaria" i "Palma" perquè poguem fer el trajecte en cotxe.

Font: Mejores Rutas

Ens interessa visitar totes les ciutats principals d'Espanya recorrent la mínima distància possible.

No cal que ho facis de forma òptima, ens interessa que desenvolupis una solució raonable utilitzant les eines que tens actualment.

Per exemple, una aproximació senzilla (que no òptima) seria anant sempre a la ciutat més propera que no haguem visitat encara

Fes una funció que donada la matriu de distàncies i la ciutat d'origen, faci una proposta de ruta que sigui el més curta possible que puguis, retornant una llista amb l'ordre de visita. Dóna també la distància total recorreguda.

(EXTRA) Des de quina ciutat la ruta seria més curta amb l'algoritme plantejat

In [1]:
import pandas as pd

# Cargamos el df usando la primera columna como los nombres de las filas ya q son las ciudades
df_rutas = pd.read_excel(r'C:\Users\aleja\Documents\Analisis de Datos\Especialidad IT ACADEMY\Sprint 10 Analítica de dades en Python\Sprint 10 ARCHIVOS\matriu_distancies.xlsx', index_col=0)

# Borramos las islas para poder viajar exclusivamente en coche
df_rutas = df_rutas.drop(index=["Palma", "Las Palmas de Gran Canaria"], 
                         columns=["Palma", "Las Palmas de Gran Canaria"])


def proponer_ruta(matriz, origen):
    # Lista de ciudades que nos faltan por visitar
    ciudades_por_visitar = list(matriz.index)
    ciudades_por_visitar.remove(origen)
    
    ruta = [origen] #creamos una lista para ir guardando las ciudades visitadas
    distancia_total = 0
    ciudad_actual = origen
    
    # El bucle se detendrá cuando la lista de pendientes se quede vacia
    while len(ciudades_por_visitar) > 0:
        # Filtramos la fila de la ciudad actual para ver solo las columnas pendientes
        distancias_opciones = matriz.loc[ciudad_actual, ciudades_por_visitar]
        
        # idxmin() nos da el nombre de la ciudad más cercana
        proxima_ciudad = distancias_opciones.idxmin()
        distancia_viaje = distancias_opciones.min()
        
        # Actualizamos las variables
        distancia_total += distancia_viaje
        ruta.append(proxima_ciudad)
        ciudades_por_visitar.remove(proxima_ciudad)
        
        # Saltamos a la nueva ciudad para la siguiente vuelta
        ciudad_actual = proxima_ciudad
        
    return ruta, distancia_total


#PROBAR CON UN ORIGEN (Ejemplo: Málaga) 
ruta_malaga, dist_malaga = proponer_ruta(df_rutas, "Málaga")
print("---  PRUEBA DE RUTA DESDE MÁLAGA ---")
print(f"Ruta propuesta: {ruta_malaga}")
print(f"Distancia total recorrida: {dist_malaga} km\n")


#RESOLVER EL (EXTRA)
# Creamos un diccionario para guardar cuánto se tarda empezando desde cada ciudad
registro_distancias = {}

for ciudad in df_rutas.index:
    #Desechamos la ruta con '_' y guardamos los kilómetros de ese viaje en 'kms'
    _, kms = proponer_ruta(df_rutas, ciudad) 
    # La clave (key) será el nombre de la ciudad y el valor (value) seran los kilómetros
    registro_distancias[ciudad] = kms

#Buscamos cuál es la ciudad que acumuló la menor distancia de todo el diccionario
mejor_origen = min(registro_distancias, key=registro_distancias.get) #con get buscamos el numero por kms y devuelve el nombre de la ciudad

print("EXTRA:")
print(f"La mejor ciudad para iniciar la ruta es: {mejor_origen}")
print(f"Consigue recorrer España entera haciendo solo: {registro_distancias[mejor_origen]} km")

---  PRUEBA DE RUTA DESDE MÁLAGA ---
Ruta propuesta: ['Málaga', 'Córdoba', 'Sevilla', 'Murcia', 'Alicante', 'Valencia', 'Zaragoza', 'Bilbao', 'Gijón', 'Valladolid', 'Vigo', 'Hospitalet de Llobregat', 'Barcelona']
Distancia total recorrida: 3066.0 km

EXTRA:
La mejor ciudad para iniciar la ruta es: Barcelona
Consigue recorrer España entera haciendo solo: 2778.0 km